# Generated by Django 5.1.7 on 2025-03-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_compeleted_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('task_descr', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Compeleted_task',
        ),
    ]
